### Create Review 1

POST http://localhost:8080/api/reviews HTTP/1.1
Content-Type: application/json

{
  "classTemplate": {
    "template_id": 1
  },
  "comment": "Great class for beginners",
  "rating": 5,
  "replyText": null,
  "student": {
    "userId": 1
  }
}


### Create Review 2

POST http://localhost:8080/api/reviews HTTP/1.1
Content-Type: application/json

{
  "classTemplate": {
    "template_id": 1
  },
  "comment": "Good pacing and instruction",
  "rating": 4,
  "replyText": null,
  "student": {
    "userId": 1
  }
}


### Get all reviews

GET http://localhost:8080/api/reviews HTTP/1.1


### Get review with id 1

GET http://localhost:8080/api/reviews/1 HTTP/1.1


### Get reviews by class template id 1

GET http://localhost:8080/api/reviews/class-template/1 HTTP/1.1


### Update review 1 with reply text

PUT http://localhost:8080/api/reviews/1 HTTP/1.1
Content-Type: application/json

{
  "replyText": "Thank you for the feedback!"
}


### Verify review 1 was updated

GET http://localhost:8080/api/reviews/1 HTTP/1.1


### Delete review 2

DELETE http://localhost:8080/api/reviews/2 HTTP/1.1


### Verify remaining reviews

GET http://localhost:8080/api/reviews HTTP/1.1
