### Create Student 1 (user 4)

POST http://localhost:8080/api/students HTTP/1.1
Content-Type: application/json

{
  "email": "dana@uncg.edu",
  "name": "Dana Green",
  "passwordHash": "danahash",
  "role": "STUDENT"
}


### Create Student 2 (user 5)

POST http://localhost:8080/api/students HTTP/1.1
Content-Type: application/json

{
  "email": "eli@uncg.edu",
  "name": "Eli Brown",
  "passwordHash": "elihash",
  "role": "STUDENT"
}


### Get all students

GET http://localhost:8080/api/students HTTP/1.1


### Get student with id 4

GET http://localhost:8080/api/students/4 HTTP/1.1


### Get student by email

GET http://localhost:8080/api/students/email/dana@uncg.edu HTTP/1.1


### Update student 2 (user 5) email only

PUT http://localhost:8080/api/students/5 HTTP/1.1
Content-Type: application/json

{
  "email": "eli_new@uncg.edu"
}


### Verify student 2 (user 5) was updated

GET http://localhost:8080/api/students/5 HTTP/1.1


### Verify remaining students

GET http://localhost:8080/api/students HTTP/1.1
