### Create Instructor 1

POST http://localhost:8080/instructors HTTP/1.1
Content-Type: application/json

{
  "email": "alice@uncg.edu",
  "name": "Alice Smith",
  "passwordHash": "alicehash",
  "role": "INSTRUCTOR"
}


### Create Instructor 2

POST http://localhost:8080/instructors HTTP/1.1
Content-Type: application/json

{
  "email": "bob@uncg.edu",
  "name": "Bob Jones",
  "passwordHash": "bobhash",
  "role": "INSTRUCTOR"
}


### Create Instructor 3

POST http://localhost:8080/instructors HTTP/1.1
Content-Type: application/json

{
  "email": "cara@uncg.edu",
  "name": "Cara White",
  "passwordHash": "carahash",
  "role": "INSTRUCTOR"
}


### Get all instructors

GET http://localhost:8080/instructors HTTP/1.1


### Get instructor with userId 1

GET http://localhost:8080/instructors/1 HTTP/1.1


### Get instructor with userId 2

GET http://localhost:8080/instructors/2 HTTP/1.1


### Update instructor 2 email only

PUT http://localhost:8080/instructors/2 HTTP/1.1
Content-Type: application/json

{
  "email": "bob_new@uncg.edu"
}


### Verify instructor 2 was updated

GET http://localhost:8080/instructors/2 HTTP/1.1


### Delete instructor 3

DELETE http://localhost:8080/instructors/3 HTTP/1.1


### Verify remaining instructors after delete

GET http://localhost:8080/instructors HTTP/1.1
